import Foundation
import TreeSitter
import TreeSitterJavaScript

/// The latest ABI version that is supported by the current version of the
/// library.
///
/// When Languages are generated by the Tree-sitter CLI, they are
/// assigned an ABI version number that corresponds to the current CLI version.
/// The Tree-sitter library is generally backwards-compatible with languages
/// generated using older CLI versions, but is not forwards-compatible.
public let LANGUAGE_VERSION = TREE_SITTER_LANGUAGE_VERSION

/// The earliest ABI version that is supported by the current version of the
/// library.
public let MIN_COMPATIBLE_LANGUAGE_VERSION = TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION
//Bundle.main.url(forResource: "index", withExtension: "html", inDirectory: "games/game1")

public struct JavaScript {
    // FIXME: using namespaces in filename due to weird bundle resource location
    public static let queries = Bundle.module.urls(forResourcesWithExtension: "js.scm", subdirectory: nil)!
    public static let parser = {
        Language(tree_sitter_javascript())
    }()
}
